security:
    providers:
        platform_users:
            entity:
                class: App\Identity\Domain\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            lazy: true
            provider: platform_users
            user_checker: App\Identity\Infrastructure\Security\ProductionUserChecker
            entry_point: App\Identity\Infrastructure\Security\ApiAuthenticationEntryPoint

when@dev:
    security:
        firewalls:
            api:
                security: false
        access_control:
            - { path: ^/(_(profiler|wdt)), roles: PUBLIC_ACCESS }
            - { path: ^/health$, roles: PUBLIC_ACCESS }
            - { path: ^/api/docs, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1, roles: PUBLIC_ACCESS }

when@test:
    security:
        firewalls:
            api:
                security: false
        access_control:
            - { path: ^/health$, roles: PUBLIC_ACCESS }
            - { path: ^/api/docs, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1, roles: PUBLIC_ACCESS }

when@prod:
    security:
        firewalls:
            api:
                access_token:
                    token_handler: App\Identity\Infrastructure\Security\JwtAccessTokenHandler
        access_control:
            - { path: ^/health$, roles: PUBLIC_ACCESS }
            - { path: ^/api/docs, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1/auth, roles: PUBLIC_ACCESS }
            - { path: ^/api/v1, roles: ROLE_USER }
