<?php

declare(strict_types=1);

namespace App\Tests\Infrastructure\Doctrine;

use App\Customers\Domain\Entity\Customer;
use App\Identity\Domain\Entity\User;
use App\Organizations\Domain\Entity\Organization;
use App\Organizations\Domain\Entity\OrganizationMembership;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class IntegerIdentifierMappingTest extends KernelTestCase
{
    public function testPersistedEntitiesUseAutoGeneratedIntegerIdentifiers(): void
    {
        self::bootKernel();
        $entityManager = self::getContainer()->get(EntityManagerInterface::class);
        self::assertInstanceOf(EntityManagerInterface::class, $entityManager);

        foreach ([User::class, Organization::class, OrganizationMembership::class, Customer::class] as $class) {
            $metadata = $entityManager->getClassMetadata($class);
            self::assertSame(['id'], $metadata->getIdentifierFieldNames());
            self::assertSame('integer', $metadata->getTypeOfField('id'));
            self::assertSame(ClassMetadata::GENERATOR_TYPE_IDENTITY, $metadata->generatorType);
        }
    }
}
