<?php

declare(strict_types=1);

namespace App\Tests\Infrastructure\Doctrine;

use App\Audit\Domain\Entity\AuditLog;
use App\Credit\Domain\Entity\CreditLimit;
use App\Customers\Domain\Entity\Customer;
use App\Identity\Domain\Entity\User;
use App\Organizations\Domain\Entity\Organization;
use App\Organizations\Domain\Entity\OrganizationMembership;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\Mapping\ToOneOwningSideMapping;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class IntegerIdentifierMappingTest extends KernelTestCase
{
    public function testPersistedEntitiesUseAutoGeneratedIntegerIdentifiers(): void
    {
        self::bootKernel();
        $entityManager = self::getContainer()->get(EntityManagerInterface::class);
        self::assertInstanceOf(EntityManagerInterface::class, $entityManager);

        foreach ([User::class, Organization::class, OrganizationMembership::class, Customer::class, CreditLimit::class, AuditLog::class] as $class) {
            $metadata = $entityManager->getClassMetadata($class);
            self::assertSame(['id'], $metadata->getIdentifierFieldNames());
            self::assertSame('integer', $metadata->getTypeOfField('id'));
            self::assertSame(ClassMetadata::GENERATOR_TYPE_IDENTITY, $metadata->generatorType);
            self::assertTrue($metadata->getFieldMapping('id')->options['unsigned'] ?? false);
        }

        foreach ([
            [OrganizationMembership::class, 'organization', Organization::class],
            [OrganizationMembership::class, 'user', User::class],
            [Customer::class, 'organization', Organization::class],
            [CreditLimit::class, 'organization', Organization::class],
            [CreditLimit::class, 'customer', Customer::class],
            [CreditLimit::class, 'approvedBy', User::class],
            [AuditLog::class, 'organization', Organization::class],
            [AuditLog::class, 'user', User::class],
        ] as [$class, $association, $target]) {
            $mapping = $entityManager->getClassMetadata($class)->getAssociationMapping($association);
            self::assertInstanceOf(ToOneOwningSideMapping::class, $mapping);
            self::assertSame($target, $mapping->targetEntity);
            self::assertCount(1, $mapping->joinColumns);
            self::assertSame('id', $mapping->joinColumns[0]->referencedColumnName);
            self::assertTrue($mapping->joinColumns[0]->options['unsigned'] ?? false);
        }

        $customerMetadata = $entityManager->getClassMetadata(Customer::class);
        $organizationMapping = $customerMetadata->getAssociationMapping('organization');
        self::assertInstanceOf(ToOneOwningSideMapping::class, $organizationMapping);
        self::assertFalse($organizationMapping->joinColumns[0]->nullable);
        self::assertSame('RESTRICT', $organizationMapping->joinColumns[0]->onDelete);
        self::assertSame(
            ['organization_id', 'document'],
            $customerMetadata->table['uniqueConstraints']['uniq_customer_organization_document']['columns'] ?? null,
        );

        $creditLimitMetadata = $entityManager->getClassMetadata(CreditLimit::class);
        self::assertSame(
            ['organization_id'],
            $creditLimitMetadata->table['indexes']['idx_credit_limit_organization']['columns'] ?? null,
        );
        $auditLogMetadata = $entityManager->getClassMetadata(AuditLog::class);
        self::assertSame(
            ['organization_id'],
            $auditLogMetadata->table['indexes']['idx_audit_organization']['columns'] ?? null,
        );
    }
}
