parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Organizations\Application\Context\OrganizationContextInterface:
        alias: App\Organizations\Application\Context\OrganizationContext
